### ISSUE TITLE
use github actions to push the contents to s3

### ISSUE THREAD

**Issue by tcheinen** [tamucybersec/cybr.club#15]
I assume we're manually syncing it right now?  imo thats a lot of work we could foist on the robots. see something like https://github.com/marketplace/actions/s3-sync. I'm pretty familiar with github actions so if this is something you want to do & need help feel free to ping me.

**Comment by matthewle0xff** [comment]
We are using AWS CodePipeline for this currently. If you want, you can ask Johnathan about the details, he's the one who set it up.
