### ISSUE TITLE
put the "get involved" modal behind localstore or a cookie or something

### ISSUE THREAD

**Issue by tcheinen** [tamucybersec/cybr.club#17]
currently it just pops up every time you visit the page and it's kinda annoying to dismiss it every page view. maybe lock it behind a cookie that expires in a week to rate limit how often they have to see it?

**Comment by matthewle0xff** [comment]
Added some js with localstore for do not show again button. Will change it later to reappear after a certain amount of time has passed but right now it is a one time do not show again button

**Comment by tcheinen** [comment]
if you do change it to be on a timer, i think you should use cookies bc those can set to expire
